### ISSUE TITLE
Show `max` cardinality only when `min` is `nil`

### ISSUE THREAD

**Issue by kwkwan** [lutaml/lutaml#100]
When `min` is not `nil`, the cardinality should shows `min..max` where `LOWER_VALUE_MAPPING` should applies on `min`.

i.e. "C" => "0" and "M" => "1"

**Comment by ronaldtse** [comment]
Let’s also not use “C” and “M”, “max” and “min”, no one knows what they mean. 

We should just use the default UML syntax in one string (no more separate cells):

* [0], [N]
* [0..N]
* [0..*]
* [N..*]

**Comment by kwkwan** [comment]
> Let’s also not use “C” and “M”, “max” and “min”, no one knows what they mean.
> 
> We should just use the default UML syntax in one string (no more separate cells):
> 
> * [0], [N]
> * [0..N]
> * [0..*]
> * [N..*]

Does N mean nil?

**Comment by kwkwan** [comment]
Closed as replaced by https://github.com/lutaml/lutaml/issues/101.

**Comment by ronaldtse** [comment]
N is any number.
