### ISSUE TITLE
Update minimum Ruby version to 2.7

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/lutaml#41]
As title.

**Comment by ronaldtse** [comment]
* [ ] https://github.com/lutaml/lutaml-sysml/issues/2
* [ ] https://github.com/lutaml/lutaml-xmi/issues/16
* [ ] https://github.com/lutaml/lutaml-express/issues/10
* [ ] https://github.com/lutaml/lutaml-uml/issues/101

**Comment by merceroncode** [comment]
All of them work great on 3.1 and all versions between 2.7 and it. Added this to Gemfile.

**Comment by ronaldtse** [comment]
@merceroncode can you please refer to https://github.com/lutaml/lutaml-express/pull/14 on how to change Ruby version? Thanks.

**Comment by ronaldtse** [comment]
Fixed in #45 .
