### ISSUE TITLE
Plan adding  support for XML parsing and Shale-type mapping.

### ISSUE THREAD

**Issue by HassanAkbar** [lutaml/lutaml#47]
Agree with the enhancement. However, I think we should probably collect these enhancements to Shale in another location, and instead of a mix-and-match of using Shale class vs this overridden class, we should only use the overridden class.

In fact, I want to enhance our LutaML gem to support Ruby object access such as Shale does. LutaML already provides a way to define a data model, we just need to extend it to support XML parsing and Shale-type mapping.

The conclusion is I'd like to update the LutaML gem to contain this Shale hack... @HassanAkbar can you help plan this feature at LutaML?

_Originally posted by @ronaldtse in https://github.com/metanorma/sts-ruby/pull/7#discussion_r1460256133_

**Comment by HassanAkbar** [comment]
@ronaldtse by looking at the `lutaml` gem structure it seems like that I will have to add a new gem named `lutaml-xml` and then add all the functionality over there.

What are your thoughts about this architecture?

**Comment by ronaldtse** [comment]
@HassanAkbar How about we just add it in `lutaml`? We can always extract it out later.

**Comment by HassanAkbar** [comment]
> @HassanAkbar How about we just add it in `lutaml`? We can always extract it out later.

@ronaldtse Sure, we can do that as well. I'll start working on adding this to the `lutaml` gem right away.
